# Generated by Django 5.2.8 on 2025-12-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('available_copies__lte', models.F('total_copies'))), name='available_not_exceed_total'),
        ),
    ]
